##############  OUTPUT FILES  #############
CSOUND_CSD_FILEPATH = 'output/output.csd'
CSOUND_RENDER_FILEPATH = 'output/output.aiff'
LOG_FILEPATH = 'output/log.txt'
HTML_LOG_FILEPATH = 'output/log.html'
MIDI_FILEPATH = 'output/output.mid'
MIDIFILE_TEMPO = 60.
TARGET_SEGMENT_LABELS_FILEPATH = 'output/targetlabels.txt'
TARGET_SEGMENTATION_GRAPH_FILEPATH = None #'output/targetlabels.jpg'
OUTPUT_LABEL_FILEPATH = 'output/outputlabels.txt'
LISP_OUTPUT_FILEPATH = None #'output/output.lisp.txt'
DATA_FROM_SEGMENTATION_FILEPATH = None #'output/datafromsegmentation.txt'
DICT_OUTPUT_FILEPATH = 'output/output.json'
MAXMSP_OUTPUT_FILEPATH = 'output/output.maxmsp.json'
TARGET_DESCRIPTORS_FILEPATH = None # 'output/targetdescriptors.json'
TARGET_PLOT_DESCRIPTORS_FILEPATH = None #'output/targetplot.jpg'
CORPUS_SEGMENTED_FEATURES_JSON_FILEPATH = None

##########  CORPUS   #######
SEARCH = []
CORPUS_GLOBAL_ATTRIBUTES = {}
VOICE_PATTERN = []
VOICE_TO_ONSET_MAPPING = []
ROTATE_VOICES = False
ORDER_CORPUS_BY_DESCRIPTOR = None
RESTRICT_CORPUS_SELECT_PERCENTAGE_BY_STRING = {}
RESTRICT_CORPUS_OVERLAP_BY_STRING = {}

#######  CONCATENATE SELECTION  #######
SUPERIMPOSE = si()
NORMALIZATION_DELTA_FREEDOM = 0 # 0=default stddev
ALWAYS_MAKE_COMPLETE_MATCHING_RESULTS = False
RANDOMIZE_AMPLITUDE_FOR_SIM_SELECTION = False
RANDOM_SEED = None
OUTPUT_GAIN_DB = 0.
OUTPUT_TIME_STRETCH = 1.
OUTPUT_TIME_ADD = 0.
OUTPUT_QUANTIZE_TIME_METHOD = None # 'snapToGrid' 'medianAggregate'
OUTPUT_QUANTIZE_TIME_INTERVAL = 0.25
CLUSTER_MAPPING = {}

############  CSOUND RENDERING  ############
CSOUND_SR = 48000
CSOUND_KSMPS = 128
CSOUND_BITS = 16
CSOUND_CHANNEL_RENDER_METHOD = "mix" # mix | oneChannelPerVoice | oneChannelPerOverlap
CSOUND_STRETCH_CORPUS_TO_TARGET_DUR = None # None | transpose | pv
CSOUND_ALIGN_PEAKS = False 
CSOUND_RENDER_DUR = 'cps' # cps | tgt
CSOUND_PLAY_RENDERED_FILE = True
CSOUND_NORMALIZE = False
CSOUND_NORMALIZE_PEAK_DB = -3

################  DESCRIPTOR COMPUTATION SETTINGS  ################
DESCRIPTOR_OVERRIDE_DATA_PATH = None
DESCRIPTOR_FORCE_ANALYSIS = False
DESCRIPTOR_WIN_SIZE_SEC = 0.04096
DESCRIPTOR_HOP_SIZE_SEC = 0.01024
# ircamdescriptor
IRCAMDESCRIPTOR_RESAMPLE_RATE = 12500
IRCAMDESCRIPTOR_WINDOW_TYPE = 'blackman'
IRCAMDESCRIPTOR_NUMB_MFCCS = 13
IRCAMDESCRIPTOR_F0_MAX_ANALYSIS_FREQ = 5000
IRCAMDESCRIPTOR_F0_MIN_FREQUENCY = 20
IRCAMDESCRIPTOR_F0_MAX_FREQUENCY = 5000
IRCAMDESCRIPTOR_F0_AMP_THRESHOLD = 30
IRCAMDESCRIPTOR_F0_QUALITY = 0.1
# other binary locations - None means disabled, otherwise specify a full path
SUPERVP_BIN = None
PM2_BIN = None

###############  USER INTERACTION / PRINTING  ##############
SEARCH_PATHS = []
VERBOSITY = 2
PRINT_SELECTION_HISTO = False
PRINT_SIM_SELECTION_HISTO = True
SEGMENTATION_FILE_INFO = 'logic'